micronaut:
  serde:
    serialization:
      inclusion: ALWAYS
  application:
    name: oda-vk-service
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: ${JWKS_URI}
  executors:
    command-listener:
      type: fixed
      nThreads: 1
    event-listener:
      type: fixed
      nThreads: 1
flyway:
  datasources:
    default:
      enabled: true
endpoints:
  prometheus:
    sensitive: false
  metrics:
    sensitive: false
